Metrics/LineLength:
  Max: 160
Metrics/AbcSize:
  Max: 40
Metrics/MethodLength:
  Max: 30
Metrics/ClassLength:
  Max: 400
Style/ClassVars:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 15
Metrics/CyclomaticComplexity:
  Max: 15